controller_list:
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Revolute_5
      - Revolute_12
      - Revolute_13
      - Revolute_23
      - Revolute_26
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Revolute_30
      - Revolute_33
      - Revolute_35
      - Revolute_41
      - Revolute_43
  - name: fake_right_palm_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_left_palm_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: right_arm
    pose: origin_right_hand
  - group: left_arm
    pose: origin_left_hand